# Generated by Django 4.2 on 2023-06-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0007_alter_sepet_odendimi_odeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odeme',
            name='urunler',
            field=models.ManyToManyField(to='urunler.sepet'),
        ),
    ]
