# Generated by Django 4.2 on 2023-06-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0008_alter_odeme_urunler'),
    ]

    operations = [
        migrations.AddField(
            model_name='odeme',
            name='odendiMi',
            field=models.BooleanField(default=False),
        ),
    ]
